In [2]:
from sklearn import preprocessing
import numpy as np

### Scaling

In [3]:
X_train = np.array([[ -3., 1., 2.],
[ 2., 0., 0.],
[ 1., 2., 3.]])
X_scaled = preprocessing.scale(X_train)
print(X_scaled)

[[-1.38873015  0.          0.26726124]
 [ 0.9258201  -1.22474487 -1.33630621]
 [ 0.46291005  1.22474487  1.06904497]]


In [4]:
import gym

In [5]:
env = gym.make('CartPole-v0')
#env = gym.make('SpaceInvaders-v0')

In [58]:
observation = env.reset()
obs, reward, done, info = env.step(action)
#obs
#obs[np.newaxis]
#obs.reshape(1, -1)

In [31]:
env.close()