In [18]:
import numpy as np
from numpy import linalg as LA

In [47]:
n = 8
g = 5

In [14]:
X = np.array([[53.2, 52.6, 52.7, 53.2, 52.8, 53.3, 49.7, 53.1],
[53.0, 53.1, 52.6, 53.2, 52.8, 53.6, 55.7, 53.5],
[53, 53.4, 50.6, 53.5, 52.9, 53.8, 52.7, 52.6],
[56, 53, 53.6, 53.7, 52.5, 53.2, 53.3, 52.5],
[50, 53.3, 52.8, 53.1, 52.9, 52.6, 52.7, 53.5]])

In [51]:
D = np.zeros((n, n, n))

In [63]:
for k in range(g):
    for i in range(n):
        for j in range(n):
            D[k][i][j] = np.exp(-1 * np.abs(X[k][i] - X[k][j]))

In [344]:
def get(M):
    v, T = LA.eig(M)
    v = np.round(v, 4)
    v.sort()
    v = v[::-1]
    a = [i/v.sum() for i in v]
    return v, np.round(T.T, 4), np.round(a, 4)

In [347]:
v, T, a = get(D[0])

In [348]:
a

array([ 0.6765,  0.1385,  0.1236,  0.0236,  0.0181,  0.0116,  0.0081,
       -0.    ])

In [349]:
v

array([ 5.412 ,  1.1082,  0.9891,  0.1884,  0.1446,  0.0931,  0.0645,
       -0.    ])

In [350]:
T[0]

array([0.3971, 0.3397, 0.3628, 0.3971, 0.3761, 0.3717, 0.0229, 0.397 ])

In [325]:
T[1]

array([ 0.3256, -0.4914, -0.4516,  0.3256, -0.3346,  0.3522, -0.2693,
        0.1845])

In [326]:
T[2]

array([ 0.0822, -0.1395, -0.1366,  0.0822, -0.1075,  0.091 ,  0.9627,
        0.0408])

In [327]:
0.3971 * D[0][0][0] + 0.3397 * D[0][0][1] + 0.3628 * D[0][0][2] + 0.3971 * D[0][0][3] + 0.3761 * D[0][0][4] + 0.3717 * D[0][0][5] + 0.0229 * D[0][0][6] + 0.3970 * D[0][0][7]

2.149028048763501

In [328]:
0.3256 * D[0][0][0] - 0.4914 * D[0][0][1] - 0.4516 * D[0][0][2] + 0.3256 * D[0][0][3] - 0.3346 * D[0][0][4] + 0.3522 * D[0][0][5] - 0.2693 * D[0][0][6] + 0.1845 * D[0][0][7]

0.3608097155979177

In [329]:
def getISDS(D, T, m = 3):
    z = np.zeros((n))
    y = np.zeros((n, m))

    for i in range(n):
        for j in range(m):
            y[i][j] = T[j] @ D[i][i]
    
    for i in range(n):
        z[i] = np.sum(y[i] * a[0:m])
    
    return y, z

In [330]:
y, z = getISDS(D, T)
z

array([1.51383309, 1.37232702, 0.30661183, 0.98118121, 1.19938272,
       1.09354315, 0.        , 0.        ])

In [331]:
np.round(y, 4)

array([[ 2.1490e+00,  3.6080e-01,  8.1300e-02],
       [ 2.0503e+00, -1.0670e-01,  8.0000e-04],
       [ 5.5070e-01, -4.6120e-01, -1.6800e-02],
       [ 1.4075e+00, -3.0650e-01,  5.7800e-01],
       [ 1.7910e+00, -6.4640e-01,  6.2520e-01],
       [ 1.5685e+00, -4.5640e-01,  7.7390e-01],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [332]:
z

array([1.51383309, 1.37232702, 0.30661183, 0.98118121, 1.19938272,
       1.09354315, 0.        , 0.        ])

In [333]:
a[0:3]

array([0.6765, 0.1385, 0.1236])

In [339]:
a[0] * y[1][0]

1.3869997419651159

In [338]:
a[0] * y[1][0] + a[1] * y[1][1] + a[2] * y[1][2]

1.3723270234294056

In [336]:
y[0][1]

0.3608097155979177

In [351]:
v, T, a = get(D[1])
y, z = getISDS(D, T)
z

array([1.33878551, 1.31882331, 0.33059396, 0.78508538, 1.00853296,
       0.8320568 , 0.        , 0.        ])